[package]
name = "sg-multi-test"
version = "0.8.0"
edition = "2021"
authors = ["Jorge Hernandez <jorge@publicawesome.com>"]
description = "Integration test helpers for Stargaze custom contracts"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/contracts"
homepage = "https://stargaze.zone"

[dependencies]
anyhow = "1"
cw-multi-test = "0.12.1"
cosmwasm-std = { version = "1.0.0-beta5" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sg-std = "0.9.0"
